### ISSUE TITLE
Characters cut off when sign column is shown

### ISSUE THREAD

**Issue by jdmonaco** [Konfekt/FoldText#5]
For example, when I edit a latex file while running vim-signify, the sign column appears and displays per-line changes. At the same time, the `%]` at the end of the fold text is cut off on the right side of the window. The extra two columns taken up by the sign column don't seem to be accounted for in calculating the usable window width. As a workaround, I simply subtracted 2 from the width calculation on [line 20](https://github.com/Konfekt/FoldText/blob/d56075d940eb64655e3f9428514bf48c6b841d66/plugin/FoldText.vim#L20):
```vim
  let w = winwidth(0) - &foldcolumn - (&number ? &numberwidth : 0) - 2
```
In a buffer with changes, this makes the text flush with the right side; without changes (no sign column), there are extra spaces between "]" and the right edge. To prevent the extra margin (except for one character, for some reason), one option is to always leave the sign column on:
```vim
let &signcolumn='yes'
```

I don't see an obvious way to detect whether the sign column is showing. Annoyingly, `:sign list` doesn't list windows or filenames to check if any signs are placed in the current window. 
Anyway, I don't really know what I'm doing, but thought you might want to know about this. Thanks for the pretty fold text!

**Comment by Konfekt** [comment]
I am not sure how to check if the sign column is shown when `&signcolumn` is `auto` neither, but at least the setting `yes` is now taken account of.

**Comment by Konfekt** [comment]
Thank you for the detailed investigation!

**Comment by jdmonaco** [comment]
That's a pretty good solution for now! Thanks for the update.
